[supervisord]
nodaemon=true

[program:redis]
command=redis-server
autostart=true
autorestart=true
priority=1

[program:mariadb]
command=mysqld_safe
autostart=true
autorestart=true
priority=2

[program:init-site]
command=/bin/bash -c "bench new-site airplane.local --admin-password admin --db-root-password root && bench --site airplane.local install-app airplane_mode"
autostart=true
priority=3
autorestart=false

[program:frappe]
command=bench serve --port 8000 --site airplane.local
directory=/home/frappe/frappe-bench
autostart=true
autorestart=true
priority=4
