[supervisord]
nodaemon=true

[program:redis]
command=redis-server
autostart=true
autorestart=true
priority=1
user=frappe

[program:mariadb]
command=mysqld_safe
autostart=true
autorestart=true
priority=2
user=frappe

[program:init-site]
command=/bin/bash -c "sleep 10 && bench new-site airplane.local --admin-password admin --db-root-password root && bench --site airplane.local install-app airplane_mode"
directory=/home/frappe/frappe-bench
autostart=true
autorestart=false
priority=3
user=frappe

[program:frappe]
command=/bin/bash -c "bench set-config -g developer_mode 1 && bench serve --port $PORT --site airplane.local"
directory=/home/frappe/frappe-bench
autostart=true
autorestart=true
priority=4
user=frappe
